# Generated by Django 5.2.7 on 2025-10-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('acceptee', 'Acceptée'), ('annulee', 'Annulée')], default='envoyee', max_length=20)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='request.requete')),
            ],
        ),
    ]
