<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-26 13:45
=======
# Generated by Django 5.2.7 on 2025-10-23 18:21
>>>>>>> f88086fba5b460e9fa452f988372cf202d7c0f90

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('request', '__first__'),
=======
        ('request', '0001_initial'),
>>>>>>> f88086fba5b460e9fa452f988372cf202d7c0f90
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('acceptee', 'Acceptée'), ('annulee', 'Annulée')], default='envoyee', max_length=20)),
                ('requete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='request.requete')),
            ],
        ),
        migrations.CreateModel(
            name='RecevoirAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('alerte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='alert.alerte')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='users.donneur')),
            ],
        ),
    ]
