# Generated by Django 5.2.7 on 2025-10-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recevoiralerte',
            name='statut',
        ),
        migrations.AlterField(
            model_name='alerte',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('envoyee', 'Envoyée'), ('acceptee', 'Acceptée'), ('annulee', 'Annulée')], default='envoyee', max_length=20),
        ),
    ]
