# Generated by Django 5.2.7 on 2025-10-22 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
        ('users', '0003_docteur_est_verifie'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecevoirAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('alerte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='alert.alerte')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recus', to='users.donneur')),
            ],
        ),
    ]
