# Generated by Django 5.2.7 on 2025-11-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_remove_recevoiralerte_statut_alter_alerte_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='recevoiralerte',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
