# Generated by Django 5.2.7 on 2025-10-21 16:55

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanqueDeSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=255)),
                ('code_inscription', models.CharField(max_length=20, validators=[users.models.verifier_code_banc])),
                ('est_verifie', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Docteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('code_inscription', models.CharField(max_length=20, validators=[users.models.verifier_code_doc])),
                ('est_verifie', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Donneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('groupe_sanguin', models.CharField(max_length=5)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
