# Generated by Django 5.2.7 on 2025-10-22 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docteur',
            name='est_verifie',
        ),
        migrations.AddField(
            model_name='docteur',
            name='BanqueDeSang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docteurs', to='users.banquedesang'),
        ),
    ]
