# Generated by Django 5.2.7 on 2025-10-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_docteur_est_verifie_docteur_banquedesang'),
    ]

    operations = [
        migrations.AddField(
            model_name='docteur',
            name='est_verifie',
            field=models.BooleanField(default=False),
        ),
    ]
