# Generated by Django 5.2.7 on 2025-10-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alert', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_don', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('alerte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='alert.alerte')),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='users.banquedesang')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='users.donneur')),
            ],
        ),
        migrations.CreateModel(
            name='FaireDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('alerte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='alert.alerte')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='users.donneur')),
            ],
        ),
    ]
