# Generated by Django 5.2.7 on 2025-10-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecevoirAlerte',
        ),
    ]
