# Generated by Django 5.2.7 on 2025-10-30 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanqueOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('envoi_alerte', 'Envoi Alerte'), ('valide_don', 'Valide Don'), ('cancel_alerte', 'Annule Alerte')], max_length=50)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='users.banquedesang')),
            ],
        ),
    ]
