# Generated by Django 5.2.7 on 2025-10-30 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_donneur_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requete', models.DateTimeField(auto_now_add=True)),
                ('groupe_sanguin', models.CharField(max_length=5)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refusee', 'Refusee')], default='en_attente', max_length=20)),
                ('docteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requetes', to='users.docteur')),
            ],
        ),
    ]
