# Generated by Django 5.2.7 on 2025-10-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_requete_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requete',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('envoyee', 'envoyee'), ('valide', 'Validé'), ('refusee', 'Refusee')], default='en_attente', max_length=20),
        ),
    ]
